name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 18 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ⏬ Install zola
        run: sudo snap install --edge zola

      - name: 📖 Build
        run: zola build

      - name: 🤠 Publish
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
